---
- name: Copy Kibana configuration file
  template:
    src: "{{ kibana_host_config_file_path }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: kibana_config_check.stat.exists
  notify: Restart Kibana