---
- name: Set list of path to look for local kibana configuration directory
  set_fact:
    kibana_search_config_paths: "{{ kibana_search_config_paths }} + [ '{{ kibana_search_config_path }}' ]"
  with_items: "{{ group_names }}"

- name: Check if Kibana configuration directory exists
  stat:
    path: "{{ item }}"
  register: kibana_config_check
  become: false
  delegate_to: 127.0.0.1
  with_first_found:
    - files: "{{ kibana_search_config_paths }}"
      skip: true

- name: Set Kibana configuration directory
  set_fact:
    kibana_host_config_path: "{{ kibana_config_check.results[0].stat.path }}"
  when:
    - kibana_config_check.results[0] is defined
    - kibana_config_check.results[0].stat is defined
    - kibana_config_check.results[0].stat.isdir

- name: Check if Kibana configuration file is exists
  stat:
    path: "{{ kibana_host_config_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: kibana_config_check

- name: Check if Kibana SSL private key file is exists
  stat:
    path: "{{ kibana_host_ssl_key_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: kibana_ssl_key_check

- name: Check if Kibana SSL certificate file is exists
  stat:
    path: "{{ kibana_host_ssl_cert_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: kibana_ssl_cert_check

- name: Check if Kibana SSL CA file is exists
  stat:
    path: "{{ kibana_host_ssl_ca_file_path }}"
  become: false
  delegate_to: 127.0.0.1
  register: kibana_ssl_ca_check