---
- name: Install Kibana
  apt:
    name: "{{ kibana_apt_package }}"
    state: present
    update_cache: yes

- name: Ensure service enabled
  service:
    name: kibana
    enabled: yes
    state: started